// src/vue/components/LiveIndicator.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  status?: "live" | "offline" | "idle";
  label?: string;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  status: "live",
});

const statusColors = {
  live: "bg-green-500",
  offline: "bg-red-500",
  idle: "bg-yellow-500",
};

const classes = computed(() => cn("inline-flex items-center gap-1.5", props.class));
</script>

<template>
  <span :class="classes">
    <span class="relative flex h-2 w-2">
      <span
        v-if="status === 'live'"
        :class="cn('absolute inline-flex h-full w-full animate-ping rounded-full opacity-75', statusColors[status])"
      />
      <span :class="cn('relative inline-flex h-2 w-2 rounded-full', statusColors[status])" />
    </span>
    <span v-if="label" class="text-xs font-medium text-[hsl(var(--la-muted-foreground))]">{{ label }}</span>
    <slot />
  </span>
</template>

// src/components/LiveIndicator/LiveIndicator.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/utils";

const liveIndicatorVariants = cva("inline-flex items-center font-medium", {
  variants: {
    size: {
      sm: "gap-1.5 text-xs",
      md: "gap-2 text-sm",
      lg: "gap-2.5 text-base",
    },
  },
  defaultVariants: {
    size: "md",
  },
});

const liveDotVariants = cva("rounded-full flex-shrink-0", {
  variants: {
    size: {
      sm: "h-1.5 w-1.5",
      md: "h-2 w-2",
      lg: "h-3 w-3",
    },
    status: {
      online: "bg-green-500",
      offline: "bg-[hsl(var(--la-muted-foreground))]",
      degraded: "bg-amber-400",
    },
  },
  defaultVariants: {
    size: "md",
    status: "online",
  },
});

export interface LiveIndicatorProps
  extends React.HTMLAttributes<HTMLSpanElement>,
    VariantProps<typeof liveIndicatorVariants> {
  status?: "online" | "offline" | "degraded";
  label?: string;
  pulse?: boolean;
}

function LiveIndicator({
  className,
  size,
  status = "online",
  label = "Live",
  pulse = true,
  ...props
}: LiveIndicatorProps) {
  const shouldPulse = pulse && status !== "offline";
  return (
    <span className={cn(liveIndicatorVariants({ size }), className)} {...props}>
      <span className="relative inline-flex">
        {shouldPulse && (
          <span
            className={cn(
              "absolute inline-flex animate-ping rounded-full opacity-75",
              liveDotVariants({ size, status })
            )}
          />
        )}
        <span className={cn(liveDotVariants({ size, status }))} />
      </span>
      <span>{label}</span>
    </span>
  );
}

LiveIndicator.displayName = "LiveIndicator";
export { LiveIndicator, liveIndicatorVariants, liveDotVariants };
