// src/svelte/components/AccordionContent.svelte
<script lang="ts">
import { cn } from "../utils/cn";
import { useAccordionContext, useAccordionItemContext } from "../composables/useAccordion";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



const { activeItems } = useAccordionContext();
const { value } = useAccordionItemContext();
let isOpen = $derived(activeItems.value.includes(value));
let classes = $derived(cn("overflow-hidden text-sm", className));
</script>

<div v-if="isOpen" class={classes} {...restProps}>
    <div class="pb-4 pt-0">
      {@render children?.()}
    </div>
  </div>

// src/vue/components/AccordionContent.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";
import { useAccordionContext, useAccordionItemContext } from "../composables/useAccordion";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const { activeItems } = useAccordionContext();
const { value } = useAccordionItemContext();
const isOpen = computed(() => activeItems.value.includes(value));
const classes = computed(() => cn("overflow-hidden text-sm", props.class));
</script>

<template>
  <div v-if="isOpen" :class="classes">
    <div class="pb-4 pt-0">
      <slot />
    </div>
  </div>
</template>
