// src/svelte/components/AccordionItem.svelte
<script lang="ts">
import { cn } from "../utils/cn";
import { provideAccordionItemContext, useAccordionContext } from "../composables/useAccordion";

  let { value, class: className, children, ...restProps }: {
  value: string;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



provideAccordionItemContext({ value: value });
const { activeItems } = useAccordionContext();
let isOpen = $derived(activeItems.value.includes(value));
let classes = $derived(cn("border-b border-[hsl(var(--la-border))]", className));
</script>

<div class={classes} :data-state="isOpen ? 'open' : 'closed'" {...restProps}>
    {@render children?.()}
  </div>

// src/vue/components/AccordionItem.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";
import { provideAccordionItemContext, useAccordionContext } from "../composables/useAccordion";

interface Props {
  value: string;
  class?: string;
}

const props = defineProps<Props>();
provideAccordionItemContext({ value: props.value });
const { activeItems } = useAccordionContext();
const isOpen = computed(() => activeItems.value.includes(props.value));
const classes = computed(() => cn("border-b border-[hsl(var(--la-border))]", props.class));
</script>

<template>
  <div :class="classes" :data-state="isOpen ? 'open' : 'closed'">
    <slot />
  </div>
</template>
