// src/svelte/components/AlertDescription.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("text-sm [&_p]:leading-relaxed", className));
</script>

<div class={classes} {...restProps}>
    {@render children?.()}
  </div>

// src/vue/components/AlertDescription.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("text-sm [&_p]:leading-relaxed", props.class));
</script>

<template>
  <div :class="classes">
    <slot />
  </div>
</template>
