// src/svelte/components/BreadcrumbPage.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("font-normal text-[hsl(var(--la-foreground))]", className));
</script>

<span aria-current="page" class={classes} {...restProps}>
    {@render children?.()}
  </span>

// src/vue/components/BreadcrumbPage.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("font-normal text-[hsl(var(--la-foreground))]", props.class));
</script>

<template>
  <span aria-current="page" :class="classes">
    <slot />
  </span>
</template>
