// src/svelte/components/Breadcrumb.svelte
<script lang="ts">
  import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();

  let classes = $derived(cn("flex flex-wrap items-center gap-1.5 break-words text-sm text-[hsl(var(--la-muted-foreground))] sm:gap-2.5", className));
</script>

<div class={classes} {...restProps}>
  {@render children?.()}
</div>

// src/vue/components/Breadcrumb.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("flex flex-wrap items-center gap-1.5 break-words text-sm text-[hsl(var(--la-muted-foreground))]", props.class));
</script>

<template>
  <nav aria-label="breadcrumb">
    <ol :class="classes">
      <slot />
    </ol>
  </nav>
</template>
