// src/svelte/components/CardTitle.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("text-2xl font-semibold leading-none tracking-tight", className));
</script>

<h3 class={classes} {...restProps}>
    {@render children?.()}
  </h3>

// src/vue/components/CardTitle.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("text-2xl font-semibold leading-none tracking-tight", props.class));
</script>

<template>
  <h3 :class="classes">
    <slot />
  </h3>
</template>
