// src/svelte/components/Card.svelte
<script lang="ts">
  import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();

  let classes = $derived(cn("rounded-lg border border-border bg-card text-card-foreground shadow-sm", className));
</script>

<div class={classes} {...restProps}>
  {@render children?.()}
</div>

// src/vue/components/Card.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn("rounded-[--la-radius] border border-border bg-card text-card-foreground shadow-sm", props.class),
);
</script>

<template>
  <div :class="classes">
    <slot />
  </div>
</template>
