// src/svelte/components/ScrollArea.svelte
<script lang="ts">
  import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();

  let classes = $derived(cn("relative overflow-hidden", className));
</script>

<div class={classes} {...restProps}>
  {@render children?.()}
</div>

// src/vue/components/ScrollArea.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("relative overflow-hidden", props.class));
</script>

<template>
  <div :class="classes">
    <div class="h-full w-full overflow-auto">
      <slot />
    </div>
  </div>
</template>
