// src/svelte/components/SheetTitle.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("text-lg font-semibold text-[hsl(var(--la-foreground))]", className));
</script>

<h2 class={classes} {...restProps}>
    {@render children?.()}
  </h2>

// src/vue/components/SheetTitle.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("text-lg font-semibold text-[hsl(var(--la-foreground))]", props.class));
</script>

<template>
  <h2 :class="classes">
    <slot />
  </h2>
</template>
