// src/components/Skeleton/Skeleton.tsx
import * as React from "react";
import { cn } from "../../lib/utils";

const Skeleton = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn("animate-pulse rounded-md bg-muted", className)}
      {...props}
    />
  )
);
Skeleton.displayName = "Skeleton";

export { Skeleton };

// src/vue/components/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn("animate-pulse rounded-[--la-radius] bg-muted", props.class),
);
</script>

<template>
  <div :class="classes" />
</template>
