// src/svelte/components/TableCaption.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("mt-4 text-sm text-[hsl(var(--la-muted-foreground))]", className));
</script>

<caption class={classes} {...restProps}>
    {@render children?.()}
  </caption>

// src/vue/components/TableCaption.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("mt-4 text-sm text-[hsl(var(--la-muted-foreground))]", props.class));
</script>

<template>
  <caption :class="classes">
    <slot />
  </caption>
</template>
