// src/svelte/components/TableRow.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(
cn(
    "border-b border-[hsl(var(--la-border))] transition-colors hover:bg-[hsl(var(--la-muted)/0.5)] data-[state=selected]:bg-[hsl(var(--la-muted))]",
    className,
  ),
);
</script>

<tr class={classes} {...restProps}>
    {@render children?.()}
  </tr>

// src/vue/components/TableRow.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn(
    "border-b border-[hsl(var(--la-border))] transition-colors hover:bg-[hsl(var(--la-muted)/0.5)] data-[state=selected]:bg-[hsl(var(--la-muted))]",
    props.class,
  ),
);
</script>

<template>
  <tr :class="classes">
    <slot />
  </tr>
</template>
