// src/svelte/components/TableHeader.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("[&_tr]:border-b", className));
</script>

<thead class={classes} {...restProps}>
    {@render children?.()}
  </thead>

// src/vue/components/TableHeader.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("[&_tr]:border-b", props.class));
</script>

<template>
  <thead :class="classes">
    <slot />
  </thead>
</template>
