// src/svelte/components/Tooltip.svelte
<script lang="ts">
  import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();

  let classes = $derived(cn("z-50 overflow-hidden rounded-md border border-border bg-popover px-3 py-1.5 text-xs text-popover-foreground shadow-md animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2", className));
</script>

<div class={classes} {...restProps}>
  {@render children?.()}
</div>

// src/vue/components/Tooltip.vue
<script setup lang="ts">
import { ref } from "vue";
import { cn } from "../utils/cn";

interface Props {
  content: string;
  side?: "top" | "right" | "bottom" | "left";
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  side: "top",
});

const visible = ref(false);

const sideClasses = {
  top: "bottom-full left-1/2 -translate-x-1/2 mb-2",
  right: "left-full top-1/2 -translate-y-1/2 ml-2",
  bottom: "top-full left-1/2 -translate-x-1/2 mt-2",
  left: "right-full top-1/2 -translate-y-1/2 mr-2",
};
</script>

<template>
  <div
    class="relative inline-flex"
    @mouseenter="visible = true"
    @mouseleave="visible = false"
    @focusin="visible = true"
    @focusout="visible = false"
  >
    <slot />
    <div
      v-if="visible"
      role="tooltip"
      :class="cn(
        'absolute z-50 overflow-hidden rounded-[--la-radius] border border-border bg-popover px-3 py-1.5 text-xs text-popover-foreground shadow-md whitespace-nowrap',
        sideClasses[side],
        props.class,
      )"
    >
      {{ content }}
    </div>
  </div>
</template>
