// src/vue/components/AlertTitle.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("mb-1 font-medium leading-none tracking-tight", props.class));
</script>

<template>
  <h5 :class="classes">
    <slot />
  </h5>
</template>

// src/svelte/components/AlertTitle.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("mb-1 font-medium leading-none tracking-tight", className));
</script>

<h5 class={classes} {...restProps}>
    {@render children?.()}
  </h5>
