// src/vue/components/BreadcrumbLink.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  href?: string;
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn("transition-colors hover:text-[hsl(var(--la-foreground))]", props.class),
);
</script>

<template>
  <a v-if="href" :href="href" :class="classes">
    <slot />
  </a>
  <span v-else :class="classes">
    <slot />
  </span>
</template>

// src/svelte/components/BreadcrumbLink.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { href, class: className, children, ...restProps }: {
  href?: string;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(
cn("transition-colors hover:text-[hsl(var(--la-foreground))]", className),
);
</script>

<a v-if="href" :href="href" class={classes} {...restProps}>
    {@render children?.()}
  </a>
  <span v-else class={classes}>
    {@render children?.()}
  </span>
