// src/vue/components/BreadcrumbItem.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("inline-flex items-center gap-1.5", props.class));
</script>

<template>
  <li :class="classes">
    <slot />
  </li>
</template>

// src/svelte/components/BreadcrumbItem.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("inline-flex items-center gap-1.5", className));
</script>

<li class={classes} {...restProps}>
    {@render children?.()}
  </li>
