// src/vue/components/DropdownMenuSeparator.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("-mx-1 my-1 h-px bg-[hsl(var(--la-muted))]", props.class));
</script>

<template>
  <div role="separator" :class="classes" />
</template>

// src/svelte/components/DropdownMenuSeparator.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, ...restProps }: {

    class?: string;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("-mx-1 my-1 h-px bg-[hsl(var(--la-muted))]", className));
</script>

<div role="separator" class={classes} / {...restProps}>
