// src/vue/components/DropdownMenuLabel.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  inset?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  inset: false,
});

const classes = computed(() =>
  cn("px-2 py-1.5 text-sm font-semibold", props.inset && "pl-8", props.class),
);
</script>

<template>
  <div :class="classes">
    <slot />
  </div>
</template>

// src/svelte/components/DropdownMenuLabel.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { inset = false, class: className, children, ...restProps }: {
  inset?: boolean;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();




let classes = $derived(
cn("px-2 py-1.5 text-sm font-semibold", inset && "pl-8", className),
);
</script>

<div class={classes} {...restProps}>
    {@render children?.()}
  </div>
