// src/vue/components/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn("animate-pulse rounded-[--la-radius] bg-muted", props.class),
);
</script>

<template>
  <div :class="classes" />
</template>

// src/svelte/components/Skeleton.svelte
<script lang="ts">
  import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();

  let classes = $derived(cn("animate-pulse rounded-md bg-muted", className));
</script>

<div class={classes} {...restProps}>
  {@render children?.()}
</div>
