// src/vue/components/TableBody.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn("[&_tr:last-child]:border-0", props.class));
</script>

<template>
  <tbody :class="classes">
    <slot />
  </tbody>
</template>

// src/svelte/components/TableBody.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(cn("[&_tr:last-child]:border-0", className));
</script>

<tbody class={classes} {...restProps}>
    {@render children?.()}
  </tbody>
