// src/vue/components/TableHead.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn(
    "h-12 px-4 text-left align-middle font-medium text-[hsl(var(--la-muted-foreground))] [&:has([role=checkbox])]:pr-0",
    props.class,
  ),
);
</script>

<template>
  <th :class="classes">
    <slot />
  </th>
</template>

// src/svelte/components/TableHead.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(
cn(
    "h-12 px-4 text-left align-middle font-medium text-[hsl(var(--la-muted-foreground))] [&:has([role=checkbox])]:pr-0",
    className,
  ),
);
</script>

<th class={classes} {...restProps}>
    {@render children?.()}
  </th>
