// src/vue/components/TableCell.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn("p-4 align-middle [&:has([role=checkbox])]:pr-0", props.class),
);
</script>

<template>
  <td :class="classes">
    <slot />
  </td>
</template>

// src/svelte/components/TableCell.svelte
<script lang="ts">
import { cn } from "../utils/cn";

  let { class: className, children, ...restProps }: {

    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();



let classes = $derived(
cn("p-4 align-middle [&:has([role=checkbox])]:pr-0", className),
);
</script>

<td class={classes} {...restProps}>
    {@render children?.()}
  </td>
