// src/vue/components/TabsTrigger.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";
import { useTabsContext } from "../composables/useTabs";

interface Props {
  value: string;
  disabled?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
});

const { activeTab, setActiveTab } = useTabsContext();
const isActive = computed(() => activeTab.value === props.value);

const classes = computed(() =>
  cn(
    "inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-[hsl(var(--la-background))] transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--la-ring))] focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
    isActive.value
      ? "bg-[hsl(var(--la-background))] text-[hsl(var(--la-foreground))] shadow-sm"
      : "text-[hsl(var(--la-muted-foreground))] hover:bg-[hsl(var(--la-muted))]",
    props.class,
  ),
);
</script>

<template>
  <button
    role="tab"
    :aria-selected="isActive"
    :disabled="disabled"
    :class="classes"
    @click="setActiveTab(value)"
  >
    <slot />
  </button>
</template>

// src/svelte/components/TabsTrigger.svelte
<script lang="ts">
import { cn } from "../utils/cn";
import { useTabsContext } from "../composables/useTabs";

  let { value, disabled = false, class: className, children, ...restProps }: {
  value: string;
  disabled?: boolean;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  } = $props();




const { activeTab, setActiveTab } = useTabsContext();
let isActive = $derived(activeTab.value === value);

let classes = $derived(
cn(
    "inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-[hsl(var(--la-background))] transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--la-ring))] focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
    isActive.value
      ? "bg-[hsl(var(--la-background))] text-[hsl(var(--la-foreground))] shadow-sm"
      : "text-[hsl(var(--la-muted-foreground))] hover:bg-[hsl(var(--la-muted))]",
    className,
  ),
);
</script>

<button
    role="tab"
    :aria-selected="isActive"
    disabled={disabled}
    class={classes}
    @click="setActiveTab(value)"
   {...restProps}>
    {@render children?.()}
  </button>
