// src/vue/components/Label.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "../utils/cn";

interface Props {
  for?: string;
  class?: string;
}

const props = defineProps<Props>();
const classes = computed(() =>
  cn("text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70", props.class),
);
</script>

<template>
  <label :for="props.for" :class="classes">
    <slot />
  </label>
</template>

// src/components/Label/Label.tsx
import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/utils";

const labelVariants = cva(
  "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
);

export interface LabelProps
  extends React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>,
    VariantProps<typeof labelVariants> {}

function Label({ className, ref, ...props }: LabelProps & { ref?: React.Ref<React.ComponentRef<typeof LabelPrimitive.Root>> }) {
  return (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(labelVariants(), className)}
    {...props}
  />
);
}

Label.displayName = LabelPrimitive.Root.displayName;

export { Label };
